# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd1ba4d9266789ddf0d89726f5e89276aaeab1675e18f92d0110aee6ae7f1bb11626f0ed335a93ed67e011a5fc07cc3b4b50423c2cbe5e34a9eec95b9d4b660

test:
  secret_key_base: 9fd8b34816f1abb3673bd87d84c7a2a5f32a5ad1a8b19170a09cf88e80ae85997041b2c816b6eb9be621cb20c04c987e0e9b299e80e61c17f5d72721c3b16cfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
